version: 2
jobs:
  build:
    docker:
      - image: golang:1.11-alpine
        environment:
          - CGO_ENABLED: 0

    working_directory: /go/src/github.com/springload/ecs-tool

    steps:
      - run:
          name: update and install tool dependencies
          command: |-
              apk update && apk add --no-cache git openssh-client

      - checkout

      - run:
          name: Install go dep
          command: go get -u github.com/golang/dep/cmd/dep

      - run:
          name: install go deps
          command: dep ensure -vendor-only

      - run:
          name: test
          command: go test ./... -v

      - run:
          name: build
          command: go build

      - run:
          name: print help
          command: ./ecs-tool -h
